server.port: 7002
spring.application.name: api-consumer

spring.threads.virtual.enabled: true

# Helps testing, should be set to never in production
spring.web.error.include-message: always

management:
  endpoints.web.exposure.include: health,info,circuitbreakers,circuitbreakerevents
  opentelemetry.tracing.export.otlp.endpoint: http://localhost:4318/v1/traces
  otlp.metrics.export.enabled: false
  # Skip tracing, if not required
  tracing.export.enabled: false
  tracing.sampling.probability: 1.0

#spring.ssl.bundle.jks.mykeystore:
#  key:
#    alias: localhost
#  keystore:
#    type: PKCS12
#    location: classpath:mykeystore.p12
#    password: mypassword

spring.http:
  clients:
    connect-timeout: 500ms
    read-timeout: 2000ms
#   ssl.bundle: mykeystore

  serviceclient:
    default: # default group (no load balancing)
      connect-timeout:
        nanos: 6666

    productGroup:
      base-url: http://localhost:7001
      apiversion.default: 1

    recommendationGroup:
      base-url: http://localhost:7001
      apiversion.default: 2

    reviewGroup:
      base-url: http://localhost:7001
      apiversion.default: 3
#     default-header:
#       -Accept: application/json
#     apiversion.insert.path-segment: 0

app:
  product-service:
    host: localhost
    port: 7001
    apiversion: 1
  recommendation-service:
    host: localhost
    port: 7001
    apiversion: 2
  review-service:
    host: localhost
    port: 7001
    apiversion: 3

# Suggestion from ChatGPT

#spring:
#  http:
#    serviceclient:
#      productGroup:
#        connect-timeout: 500ms
#        read-timeout: 500ms

resilience4j:
  retry:
    instances:
      productGroup:
        maxAttempts: 2
        waitDuration: 100ms

  circuitbreaker:
    instances:
      productGroup:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        automaticTransitionFromOpenToHalfOpenEnabled: true
        ignoreExceptions:
          - se.magnus.sb4labs.api.exceptions.InvalidInputException
          - se.magnus.sb4labs.api.exceptions.NotFoundException

# MY OWN CONFIG

resilience4j.timelimiter:
  instances:
    productGroup:
      timeoutDuration: 20s

spring:
  cloud:
    circuitbreaker:
      resilience4j:
        disable-time-limiter: true

########
# For RestCLient based CircuitBreaker
########

resilience4j.timelimiter.instances.product.timeoutDuration: 2s

resilience4j.retry:
  instances:
    product:
      maxAttempts: 3
      waitDuration: 1000
#      retryExceptions:
#        - org.springframework.web.client.HttpClientErrorException
#        - org.springframework.web.reactive.function.client.WebClientResponseException$InternalServerError

management.health.circuitbreakers.enabled: true

resilience4j.circuitbreaker:
  instances:
    product:
      allowHealthIndicatorToFail: false
      registerHealthIndicator: true
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 5
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      ignoreExceptions:
        - se.magnus.sb4labs.api.exceptions.InvalidInputException
        - se.magnus.sb4labs.api.exceptions.NotFoundException


#resilience4j:
#  circuitbreaker:
#    instances:
##      productGroupNew:
##        slidingWindowType: COUNT_BASED
##        slidingWindowSize: 10
##        minimumNumberOfCalls: 5
##        failureRateThreshold: 50
##        waitDurationInOpenState: 10s
##        permittedNumberOfCallsInHalfOpenState: 3
#
#      productGroup:
##        allowHealthIndicatorToFail: false
##        registerHealthIndicator: true
#        allowHealthIndicatorToFail: true
#        registerHealthIndicator: false
#        slidingWindowType: COUNT_BASED
#        slidingWindowSize: 5
#        failureRateThreshold: 50
#        waitDurationInOpenState: 10000
#        permittedNumberOfCallsInHalfOpenState: 3
#        automaticTransitionFromOpenToHalfOpenEnabled: true
#        ignoreExceptions:
#          - se.magnus.sb4labs.api.exceptions.InvalidInputException
#          - se.magnus.sb4labs.api.exceptions.NotFoundException
#

logging.level:
  root: INFO
  se.magnus: DEBUG
  io.github.resilience4j: DEBUG
  io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine: DEBUG
